Rules:
- Title: "주간보고로 이동"
  Criteria:
    - AllCriteria:
      - FileExtension: "xlsx"
      - FileNameContains: "주간업무"
  Actions:
    - MoveToFolder: "~/Documents/주간보고"
- Title: "월간보고로 이동"
  Criteria:
    - AllCriteria:
      - FileExtension: "xlsx"
      - FileNameContains: "월간업무"
  Actions:
    - MoveToFolder: "~/Documents/월간보고"
- Title: "기타 보고서로 이동"
  Criteria:
    - AnyCriteria:
      - AllCriteria:
        - FileNameContains: "aaa"
        - FileNameContains: "bbb"
      - AllCriteria:
        - FileNameContains: "ccc"
        - FileNameContains: "ddd"
  Actions:
    - MoveToFolder: "~/Documents/기타"
- Title: "파일이름 윈도우 형식으로 변경"
  Criteria:
    - AllCriteria:
      - FileExtension: "xlsx"
      - FileNameContains: "주간업무"
  Actions:
      - RunShellScript: "/opt/homebrew/bin/convmv -f utf-8 -t utf-8 --nfc --notest ${FILENAME}"